### ISSUE TITLE
The Recurring Todo Front End

### ISSUE THREAD

**Issue by lbrown51** [lbrown51/WhatDo#32]
As a user, I want to be able to setup recurring tasks by duration of time passed and by days of the week. When I click on an icon in the todo extended menu, a dialog opens that allows me to do that.

### Acceptance Criteria

- [x] Opening the extended todo shows an icon to setup recurring tasks.

- [x] When I click the icon, a dialog opens and I can select (from a dropdown), the frequency with which this task will repeat.

- [x] If the frequency is weeks, then I am presented with a list of chips representing the days of the week and an edit text representing the number of weeks in between each repetition.

- [x] If the frequency is days, then I am presented with an edit text for the number of days in between each repeat.

- [x] Upon selecting my repetition frequency information, I confirm and that information is arranged in the correct manner so as to be saved in the database.
