### ISSUE TITLE
Recurring Todo Back End

### ISSUE THREAD

**Issue by lbrown51** [lbrown51/WhatDo#33]
I want to be able to save recurring tasks in an appropriate manner in the local database.

### Acceptance Criteria

- [x] The todo entity is updated to include the necessary information about recurring tasks. A new entity might be needed.

- [x] There exists (a) method(s) in the dao for updating recurrence information and (if needed) for deleting the recurrence information.

- [x] There exists a method in the repository for updating the recurrence information.

- [x] There exists a method (if needed) in the view model for the recurrence information.

- [x] If not solved in Issue #32 the correct database calls are made when recurrence information is added.
