### ISSUE TITLE
Display Todo list as widget

### ISSUE THREAD

**Issue by lbrown51** [lbrown51/WhatDo#36]
As a user, I should be able to place a widget that displays a list of my current todos on my home screen and have that list be update-able as I finish and add todos.

### Acceptance Criteria

- [ ] I can place the todo list widget on my home screen

- [ ] I can resize the widget to the appropriate size

- [ ] The widget displays a list of upcoming todos

- [ ] Clicking on a todo opens up the app

- [ ] The widget updates as I add and remove todos
